inhibit_all_warnings!

pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'Mantle'
pod 'MBProgressHUD'
pod 'UIColor-Utilities'
pod 'JSONKit-NoWarning'
pod 'Toast'
pod 'BlocksKit'
pod 'Overline-BlocksKit'
pod 'EGOTableViewPullRefreshAndLoadMore'
pod 'crackify'
pod 'OpenUDID'
pod 'UITableView+FDTemplateLayoutCell'
pod 'PDTSimpleCalendar'
pod 'DZNEmptyDataSet'
pod 'ChameleonFramework'
pod 'SVProgressHUD'
pod 'ReactiveCocoa', '2.5'
pod 'iRate'
pod 'MSDynamicsDrawerViewController'
pod 'AKPickerView'
pod 'pop'
pod 'PKYStepper', '0.0.1'