// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class AddressBook;
@class AddressBookBuilder;
@class Person;
@class PersonBuilder;
@class PersonPhoneNumber;
@class PersonPhoneNumberBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  PersonPhoneTypeMobile = 0,
  PersonPhoneTypeHome = 1,
  PersonPhoneTypeWork = 2,
} PersonPhoneType;

BOOL PersonPhoneTypeIsValidValue(PersonPhoneType value);


@interface ARoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Person : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasEmail_:1;
  SInt32 id;
  NSString* name;
  NSString* email;
  NSMutableArray * phoneArray;
}
- (BOOL) hasName;
- (BOOL) hasId;
- (BOOL) hasEmail;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 id;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSArray * phone;
- (PersonPhoneNumber*)phoneAtIndex:(NSUInteger)index;

+ (Person*) defaultInstance;
- (Person*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PersonBuilder*) builder;
+ (PersonBuilder*) builder;
+ (PersonBuilder*) builderWithPrototype:(Person*) prototype;
- (PersonBuilder*) toBuilder;

+ (Person*) parseFromData:(NSData*) data;
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromInputStream:(NSInputStream*) input;
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PersonPhoneNumber : PBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasType_:1;
  NSString* number;
  PersonPhoneType type;
}
- (BOOL) hasNumber;
- (BOOL) hasType;
@property (readonly, strong) NSString* number;
@property (readonly) PersonPhoneType type;

+ (PersonPhoneNumber*) defaultInstance;
- (PersonPhoneNumber*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PersonPhoneNumberBuilder*) builder;
+ (PersonPhoneNumberBuilder*) builder;
+ (PersonPhoneNumberBuilder*) builderWithPrototype:(PersonPhoneNumber*) prototype;
- (PersonPhoneNumberBuilder*) toBuilder;

+ (PersonPhoneNumber*) parseFromData:(NSData*) data;
+ (PersonPhoneNumber*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersonPhoneNumber*) parseFromInputStream:(NSInputStream*) input;
+ (PersonPhoneNumber*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersonPhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PersonPhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PersonPhoneNumberBuilder : PBGeneratedMessageBuilder {
@private
  PersonPhoneNumber* result;
}

- (PersonPhoneNumber*) defaultInstance;

- (PersonPhoneNumberBuilder*) clear;
- (PersonPhoneNumberBuilder*) clone;

- (PersonPhoneNumber*) build;
- (PersonPhoneNumber*) buildPartial;

- (PersonPhoneNumberBuilder*) mergeFrom:(PersonPhoneNumber*) other;
- (PersonPhoneNumberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PersonPhoneNumberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNumber;
- (NSString*) number;
- (PersonPhoneNumberBuilder*) setNumber:(NSString*) value;
- (PersonPhoneNumberBuilder*) clearNumber;

- (BOOL) hasType;
- (PersonPhoneType) type;
- (PersonPhoneNumberBuilder*) setType:(PersonPhoneType) value;
- (PersonPhoneNumberBuilder*) clearType;
@end

@interface PersonBuilder : PBGeneratedMessageBuilder {
@private
  Person* result;
}

- (Person*) defaultInstance;

- (PersonBuilder*) clear;
- (PersonBuilder*) clone;

- (Person*) build;
- (Person*) buildPartial;

- (PersonBuilder*) mergeFrom:(Person*) other;
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PersonBuilder*) setName:(NSString*) value;
- (PersonBuilder*) clearName;

- (BOOL) hasId;
- (SInt32) id;
- (PersonBuilder*) setId:(SInt32) value;
- (PersonBuilder*) clearId;

- (BOOL) hasEmail;
- (NSString*) email;
- (PersonBuilder*) setEmail:(NSString*) value;
- (PersonBuilder*) clearEmail;

- (NSMutableArray *)phone;
- (PersonPhoneNumber*)phoneAtIndex:(NSUInteger)index;
- (PersonBuilder *)addPhone:(PersonPhoneNumber*)value;
- (PersonBuilder *)setPhoneArray:(NSArray *)array;
- (PersonBuilder *)clearPhone;
@end

@interface AddressBook : PBGeneratedMessage {
@private
  NSMutableArray * personArray;
}
@property (readonly, strong) NSArray * person;
- (Person*)personAtIndex:(NSUInteger)index;

+ (AddressBook*) defaultInstance;
- (AddressBook*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AddressBookBuilder*) builder;
+ (AddressBookBuilder*) builder;
+ (AddressBookBuilder*) builderWithPrototype:(AddressBook*) prototype;
- (AddressBookBuilder*) toBuilder;

+ (AddressBook*) parseFromData:(NSData*) data;
+ (AddressBook*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddressBook*) parseFromInputStream:(NSInputStream*) input;
+ (AddressBook*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddressBook*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AddressBook*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AddressBookBuilder : PBGeneratedMessageBuilder {
@private
  AddressBook* result;
}

- (AddressBook*) defaultInstance;

- (AddressBookBuilder*) clear;
- (AddressBookBuilder*) clone;

- (AddressBook*) build;
- (AddressBook*) buildPartial;

- (AddressBookBuilder*) mergeFrom:(AddressBook*) other;
- (AddressBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AddressBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)person;
- (Person*)personAtIndex:(NSUInteger)index;
- (AddressBookBuilder *)addPerson:(Person*)value;
- (AddressBookBuilder *)setPersonArray:(NSArray *)array;
- (AddressBookBuilder *)clearPerson;
@end


// @@protoc_insertion_point(global_scope)
