// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "A.pb.h"
// @@protoc_insertion_point(imports)

@implementation ARoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ARoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Person ()
@property (strong) NSString* name;
@property SInt32 id;
@property (strong) NSString* email;
@property (strong) NSMutableArray * phoneArray;
@end

@implementation Person

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value_ {
  hasEmail_ = !!value_;
}
@synthesize email;
@synthesize phoneArray;
@dynamic phone;
- (id) init {
  if ((self = [super init])) {
    self.name = @"";
    self.id = 0;
    self.email = @"";
  }
  return self;
}
static Person* defaultPersonInstance = nil;
+ (void) initialize {
  if (self == [Person class]) {
    defaultPersonInstance = [[Person alloc] init];
  }
}
+ (Person*) defaultInstance {
  return defaultPersonInstance;
}
- (Person*) defaultInstance {
  return defaultPersonInstance;
}
- (NSArray *)phone {
  return phoneArray;
}
- (PersonPhoneNumber*)phoneAtIndex:(NSUInteger)index {
  return [phoneArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasId) {
    return NO;
  }
  __block BOOL isInitphone = YES;
   [self.phone enumerateObjectsUsingBlock:^(PersonPhoneNumber *element, NSUInteger idx, BOOL *stop) {
    if (!element.isInitialized) {
      isInitphone = NO;
      *stop = YES;
    }
  }];
  if (!isInitphone) return isInitphone;
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasId) {
    [output writeInt32:2 value:self.id];
  }
  if (self.hasEmail) {
    [output writeString:3 value:self.email];
  }
  [self.phoneArray enumerateObjectsUsingBlock:^(PersonPhoneNumber *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:4 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasName) {
    size_ += computeStringSize(1, self.name);
  }
  if (self.hasId) {
    size_ += computeInt32Size(2, self.id);
  }
  if (self.hasEmail) {
    size_ += computeStringSize(3, self.email);
  }
  [self.phoneArray enumerateObjectsUsingBlock:^(PersonPhoneNumber *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(4, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Person*) parseFromData:(NSData*) data {
  return (Person*)[[[Person builder] mergeFromData:data] build];
}
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input {
  return (Person*)[[[Person builder] mergeFromInputStream:input] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersonBuilder*) builder {
  return [[PersonBuilder alloc] init];
}
+ (PersonBuilder*) builderWithPrototype:(Person*) prototype {
  return [[Person builder] mergeFrom:prototype];
}
- (PersonBuilder*) builder {
  return [Person builder];
}
- (PersonBuilder*) toBuilder {
  return [Person builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInteger:self.id]];
  }
  if (self.hasEmail) {
    [output appendFormat:@"%@%@: %@\n", indent, @"email", self.email];
  }
  [self.phoneArray enumerateObjectsUsingBlock:^(PersonPhoneNumber *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"phone"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Person class]]) {
    return NO;
  }
  Person *otherMessage = other;
  return
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasEmail == otherMessage.hasEmail &&
      (!self.hasEmail || [self.email isEqual:otherMessage.email]) &&
      [self.phoneArray isEqualToArray:otherMessage.phoneArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.id] hash];
  }
  if (self.hasEmail) {
    hashCode = hashCode * 31 + [self.email hash];
  }
  [self.phoneArray enumerateObjectsUsingBlock:^(PersonPhoneNumber *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

BOOL PersonPhoneTypeIsValidValue(PersonPhoneType value) {
  switch (value) {
    case PersonPhoneTypeMobile:
    case PersonPhoneTypeHome:
    case PersonPhoneTypeWork:
      return YES;
    default:
      return NO;
  }
}
@interface PersonPhoneNumber ()
@property (strong) NSString* number;
@property PersonPhoneType type;
@end

@implementation PersonPhoneNumber

- (BOOL) hasNumber {
  return !!hasNumber_;
}
- (void) setHasNumber:(BOOL) value_ {
  hasNumber_ = !!value_;
}
@synthesize number;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value_ {
  hasType_ = !!value_;
}
@synthesize type;
- (id) init {
  if ((self = [super init])) {
    self.number = @"";
    self.type = PersonPhoneTypeHome;
  }
  return self;
}
static PersonPhoneNumber* defaultPersonPhoneNumberInstance = nil;
+ (void) initialize {
  if (self == [PersonPhoneNumber class]) {
    defaultPersonPhoneNumberInstance = [[PersonPhoneNumber alloc] init];
  }
}
+ (PersonPhoneNumber*) defaultInstance {
  return defaultPersonPhoneNumberInstance;
}
- (PersonPhoneNumber*) defaultInstance {
  return defaultPersonPhoneNumberInstance;
}
- (BOOL) isInitialized {
  if (!self.hasNumber) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNumber) {
    [output writeString:1 value:self.number];
  }
  if (self.hasType) {
    [output writeEnum:2 value:self.type];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasNumber) {
    size_ += computeStringSize(1, self.number);
  }
  if (self.hasType) {
    size_ += computeEnumSize(2, self.type);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PersonPhoneNumber*) parseFromData:(NSData*) data {
  return (PersonPhoneNumber*)[[[PersonPhoneNumber builder] mergeFromData:data] build];
}
+ (PersonPhoneNumber*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersonPhoneNumber*)[[[PersonPhoneNumber builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PersonPhoneNumber*) parseFromInputStream:(NSInputStream*) input {
  return (PersonPhoneNumber*)[[[PersonPhoneNumber builder] mergeFromInputStream:input] build];
}
+ (PersonPhoneNumber*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersonPhoneNumber*)[[[PersonPhoneNumber builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersonPhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PersonPhoneNumber*)[[[PersonPhoneNumber builder] mergeFromCodedInputStream:input] build];
}
+ (PersonPhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersonPhoneNumber*)[[[PersonPhoneNumber builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersonPhoneNumberBuilder*) builder {
  return [[PersonPhoneNumberBuilder alloc] init];
}
+ (PersonPhoneNumberBuilder*) builderWithPrototype:(PersonPhoneNumber*) prototype {
  return [[PersonPhoneNumber builder] mergeFrom:prototype];
}
- (PersonPhoneNumberBuilder*) builder {
  return [PersonPhoneNumber builder];
}
- (PersonPhoneNumberBuilder*) toBuilder {
  return [PersonPhoneNumber builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasNumber) {
    [output appendFormat:@"%@%@: %@\n", indent, @"number", self.number];
  }
  if (self.hasType) {
    [output appendFormat:@"%@%@: %d\n", indent, @"type", self.type];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PersonPhoneNumber class]]) {
    return NO;
  }
  PersonPhoneNumber *otherMessage = other;
  return
      self.hasNumber == otherMessage.hasNumber &&
      (!self.hasNumber || [self.number isEqual:otherMessage.number]) &&
      self.hasType == otherMessage.hasType &&
      (!self.hasType || self.type == otherMessage.type) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasNumber) {
    hashCode = hashCode * 31 + [self.number hash];
  }
  if (self.hasType) {
    hashCode = hashCode * 31 + self.type;
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PersonPhoneNumberBuilder()
@property (strong) PersonPhoneNumber* result;
@end

@implementation PersonPhoneNumberBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PersonPhoneNumber alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PersonPhoneNumberBuilder*) clear {
  self.result = [[PersonPhoneNumber alloc] init];
  return self;
}
- (PersonPhoneNumberBuilder*) clone {
  return [PersonPhoneNumber builderWithPrototype:result];
}
- (PersonPhoneNumber*) defaultInstance {
  return [PersonPhoneNumber defaultInstance];
}
- (PersonPhoneNumber*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PersonPhoneNumber*) buildPartial {
  PersonPhoneNumber* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PersonPhoneNumberBuilder*) mergeFrom:(PersonPhoneNumber*) other {
  if (other == [PersonPhoneNumber defaultInstance]) {
    return self;
  }
  if (other.hasNumber) {
    [self setNumber:other.number];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PersonPhoneNumberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PersonPhoneNumberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setNumber:[input readString]];
        break;
      }
      case 16: {
        PersonPhoneType value = (PersonPhoneType)[input readEnum];
        if (PersonPhoneTypeIsValidValue(value)) {
          [self setType:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasNumber {
  return result.hasNumber;
}
- (NSString*) number {
  return result.number;
}
- (PersonPhoneNumberBuilder*) setNumber:(NSString*) value {
  result.hasNumber = YES;
  result.number = value;
  return self;
}
- (PersonPhoneNumberBuilder*) clearNumber {
  result.hasNumber = NO;
  result.number = @"";
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (PersonPhoneType) type {
  return result.type;
}
- (PersonPhoneNumberBuilder*) setType:(PersonPhoneType) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (PersonPhoneNumberBuilder*) clearType {
  result.hasType = NO;
  result.type = PersonPhoneTypeHome;
  return self;
}
@end

@interface PersonBuilder()
@property (strong) Person* result;
@end

@implementation PersonBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[Person alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PersonBuilder*) clear {
  self.result = [[Person alloc] init];
  return self;
}
- (PersonBuilder*) clone {
  return [Person builderWithPrototype:result];
}
- (Person*) defaultInstance {
  return [Person defaultInstance];
}
- (Person*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Person*) buildPartial {
  Person* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PersonBuilder*) mergeFrom:(Person*) other {
  if (other == [Person defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.phoneArray.count > 0) {
    if (result.phoneArray == nil) {
      result.phoneArray = [[NSMutableArray alloc] initWithArray:other.phoneArray];
    } else {
      [result.phoneArray addObjectsFromArray:other.phoneArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 16: {
        [self setId:[input readInt32]];
        break;
      }
      case 26: {
        [self setEmail:[input readString]];
        break;
      }
      case 34: {
        PersonPhoneNumberBuilder* subBuilder = [PersonPhoneNumber builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addPhone:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (PersonBuilder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (PersonBuilder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasId {
  return result.hasId;
}
- (SInt32) id {
  return result.id;
}
- (PersonBuilder*) setId:(SInt32) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (PersonBuilder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (PersonBuilder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (PersonBuilder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (NSMutableArray *)phone {
  return result.phoneArray;
}
- (PersonPhoneNumber*)phoneAtIndex:(NSUInteger)index {
  return [result phoneAtIndex:index];
}
- (PersonBuilder *)addPhone:(PersonPhoneNumber*)value {
  if (result.phoneArray == nil) {
    result.phoneArray = [[NSMutableArray alloc]init];
  }
  [result.phoneArray addObject:value];
  return self;
}
- (PersonBuilder *)setPhoneArray:(NSArray *)array {
  result.phoneArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (PersonBuilder *)clearPhone {
  result.phoneArray = nil;
  return self;
}
@end

@interface AddressBook ()
@property (strong) NSMutableArray * personArray;
@end

@implementation AddressBook

@synthesize personArray;
@dynamic person;
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static AddressBook* defaultAddressBookInstance = nil;
+ (void) initialize {
  if (self == [AddressBook class]) {
    defaultAddressBookInstance = [[AddressBook alloc] init];
  }
}
+ (AddressBook*) defaultInstance {
  return defaultAddressBookInstance;
}
- (AddressBook*) defaultInstance {
  return defaultAddressBookInstance;
}
- (NSArray *)person {
  return personArray;
}
- (Person*)personAtIndex:(NSUInteger)index {
  return [personArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  __block BOOL isInitperson = YES;
   [self.person enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    if (!element.isInitialized) {
      isInitperson = NO;
      *stop = YES;
    }
  }];
  if (!isInitperson) return isInitperson;
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:1 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(1, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (AddressBook*) parseFromData:(NSData*) data {
  return (AddressBook*)[[[AddressBook builder] mergeFromData:data] build];
}
+ (AddressBook*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AddressBook*)[[[AddressBook builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (AddressBook*) parseFromInputStream:(NSInputStream*) input {
  return (AddressBook*)[[[AddressBook builder] mergeFromInputStream:input] build];
}
+ (AddressBook*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AddressBook*)[[[AddressBook builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AddressBook*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (AddressBook*)[[[AddressBook builder] mergeFromCodedInputStream:input] build];
}
+ (AddressBook*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AddressBook*)[[[AddressBook builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AddressBookBuilder*) builder {
  return [[AddressBookBuilder alloc] init];
}
+ (AddressBookBuilder*) builderWithPrototype:(AddressBook*) prototype {
  return [[AddressBook builder] mergeFrom:prototype];
}
- (AddressBookBuilder*) builder {
  return [AddressBook builder];
}
- (AddressBookBuilder*) toBuilder {
  return [AddressBook builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"person"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[AddressBook class]]) {
    return NO;
  }
  AddressBook *otherMessage = other;
  return
      [self.personArray isEqualToArray:otherMessage.personArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface AddressBookBuilder()
@property (strong) AddressBook* result;
@end

@implementation AddressBookBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[AddressBook alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (AddressBookBuilder*) clear {
  self.result = [[AddressBook alloc] init];
  return self;
}
- (AddressBookBuilder*) clone {
  return [AddressBook builderWithPrototype:result];
}
- (AddressBook*) defaultInstance {
  return [AddressBook defaultInstance];
}
- (AddressBook*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (AddressBook*) buildPartial {
  AddressBook* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (AddressBookBuilder*) mergeFrom:(AddressBook*) other {
  if (other == [AddressBook defaultInstance]) {
    return self;
  }
  if (other.personArray.count > 0) {
    if (result.personArray == nil) {
      result.personArray = [[NSMutableArray alloc] initWithArray:other.personArray];
    } else {
      [result.personArray addObjectsFromArray:other.personArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (AddressBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (AddressBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        PersonBuilder* subBuilder = [Person builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addPerson:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSMutableArray *)person {
  return result.personArray;
}
- (Person*)personAtIndex:(NSUInteger)index {
  return [result personAtIndex:index];
}
- (AddressBookBuilder *)addPerson:(Person*)value {
  if (result.personArray == nil) {
    result.personArray = [[NSMutableArray alloc]init];
  }
  [result.personArray addObject:value];
  return self;
}
- (AddressBookBuilder *)setPersonArray:(NSArray *)array {
  result.personArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (AddressBookBuilder *)clearPerson {
  result.personArray = nil;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
